### PR TITLE
This branch is for Redmine4.1.x

### PR DESCRIPTION
**Pull request by ghost**
Improved to work on Redmine 4.0 & 4.1.

### CODE REVIEW

**Comment by atvirasvilnius** [comment]
who can merge?

**Comment by n0nel** [comment]
> who can merge?

This patch is for life extension.
Because of the old style of code, it can sometimes be very slow.

**Comment by alexmonteiro** [comment]
Thank you guys!

**Comment by atvirasvilnius** [comment]
thanks

**Pull request merged**
